# NumPy

NumPy is a Python package used for scientific computing. It provides high-performance array objects and various tools for working with these arrays.

Advantages of NumPy include:

* Efficient storage and manipulation of large arrays of data.
* Mathematical operations can be performed on entire arrays at once, which is faster than performing the same operations on each element of an array individually.
* Broadcasting, which allows for arithmetic operations between arrays of different shapes and sizes.
* Compatibility with a wide variety of other Python packages used in scientific computing, such as SciPy, Matplotlib, and Pandas.

## Numpy Arrays  
NumPy arrays are used for storing and manipulating large arrays of numerical data. Creating a NumPy array can be done by passing a list, tuple or array-like object to the `numpy.array()` function. Numpy arrays can be indexed and manipulated in a variety of ways. Basic operations with arrays include arithmetic operations, logical operations, and statistical operations.

Multidimensional arrays can also be created, these are arrays with more than one dimension, and can be thought of as matrices or tensors. NumPy provides tools for creating and manipulating multidimensional arrays, as well as performing linear algebra operations on them.

Here is an example of a one-dimensional array and a two-didimensional array:

In [2]:
import numpy as np # import numpy library, and use np as alias (this is a convention)

# create a one-dimensional array
a = np.array([1, 2, 3])

# create a two-dimensional array
b = np.array([[1, 2, 3], [4, 5, 6]])

|1|2|3|
|--|--|--|
|4|5|6|


In [3]:
a

array([1, 2, 3])

In [4]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

Indexing a NumPy array is similar to indexing a regular Python list. For example:

In [6]:
# access the second element of a one-dimensional array
print(a[1])

# access the element in the first row, second column of a two-dimensional array
print(b[0, 1])

2
2


In [13]:
np.zeros((2,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [14]:
np.ones((2,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [17]:
np.full((2,5,5), (5,6,7,8,9))

array([[[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]],

       [[5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9],
        [5, 6, 7, 8, 9]]])

In [19]:
np.random.random((5,5)) * 100

array([[27.63093004, 66.91587282, 49.78332954, 49.48376953, 26.66776191],
       [ 5.50190845, 59.61239113, 63.26809163, 48.13913492, 43.68807751],
       [92.43343064, 63.83096739, 10.1558528 , 43.34164894, 23.4522932 ],
       [39.77790017, 43.6053735 ,  9.00802013, 76.48252687, 57.57413886],
       [39.57275   , 73.79872319, 25.12621982, 19.24724167, 84.87510145]])

In [21]:
type(b)

numpy.ndarray

In [23]:

print(b.tolist(), type(b.tolist()))

[[1, 2, 3], [4, 5, 6]] <class 'list'>


NumPy arrays can also be manipulated using various methods and functions. Some examples of basic operations that can be performed with arrays include element-wise arithmetic operations:

In [24]:
a, b

(array([1, 2, 3]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [25]:
# add two arrays element-wise
c = a + b

# multiply two arrays element-wise
d = a * b

In [26]:
c

array([[2, 4, 6],
       [5, 7, 9]])

In [29]:
b.shape

(2, 3)

In [31]:
b + np.array([1,2,3,4])

ValueError: operands could not be broadcast together with shapes (2,3) (4,) 

In [32]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
d

array([[ 1,  4,  9],
       [ 4, 10, 18]])

Logical operations can also be performed with arrays:

In [33]:
# create a boolean array based on a condition
e = (a > 2)

# use boolean indexing to select elements from an array
f = a[e]

In [37]:
a, e

(array([1, 2, 3]), array([False, False,  True]))

In [35]:
e.dtype

dtype('bool')

In [38]:
f

array([3])

NumPy arrays can have any number of dimensions, but are commonly used for two-dimensional arrays (matrices) and three-dimensional arrays (tensors). Multidimensional arrays can be indexed and manipulated in a similar way to one-dimensional arrays:

In [39]:
# create a three-dimensional array
g = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# access an element in the second row, first column, and second "layer"
print(g[1, 0, 1])

# compute the sum of each row in a two-dimensional array
h = np.sum(b, axis=1)

6


In [41]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
np.sum(b, axis=0)

array([5, 7, 9])

In [40]:
h

array([ 6, 15])

Can you guess what happened in the code above? Let’s break it down.

## Universal Functions
NumPy provides a range of mathematical functions, called "universal functions", that can be applied to an entire array at once, making computations much faster and more efficient.


In [43]:
arr = np.array([1, 2, 3, 4, 5])

# Applying the square root function to all elements in the array
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

# Applying the exponential function to all elements in the array
exp_arr = np.exp(arr)
print(exp_arr)

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]



## Broadcasting
Broadcasting is the process by which NumPy automatically handles operations between arrays of different shapes and sizes. This means that arrays can be added, subtracted, multiplied, and divided element-wise even if they are different sizes or shapes.


In [44]:
# Broadcasting a scalar to an array
scalar = 2
broadcasted_arr = arr * scalar
print(broadcasted_arr)

# Broadcasting arrays of different shapes
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([10, 20])
broadcasted_arr = arr1 + arr2
print(broadcasted_arr)

[ 2  4  6  8 10]
[[11 22]
 [13 24]]



## Array Shape Manipulation
NumPy provides a variety of functions for reshaping arrays, including changing their dimensions, rearranging elements, and combining arrays.


In [46]:
arr.reshape(1, 3)

ValueError: cannot reshape array of size 6 into shape (1,3)

In [45]:
# Reshaping an array
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

# Flattening an array
flattened_arr = reshaped_arr.flatten()
print(flattened_arr)

# Transposing an array
transposed_arr = reshaped_arr.T
print(transposed_arr)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]



## Masking and Boolean Logic
NumPy arrays can be used to represent Boolean values and can be used for logical operations such as AND, OR, and NOT. They can also be used for masking, which is the process of setting certain elements in an array to a specific value based on a Boolean condition.


In [47]:
# Creating a masked array
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, False])
masked_arr = np.ma.masked_array(arr, mask)
print(masked_arr)

# Boolean logic with arrays
arr1 = np.array([True, False, True, False])
arr2 = np.array([False, True, False, True])
print(np.logical_and(arr1, arr2))
print(np.logical_or(arr1, arr2))
print(np.logical_not(arr1))

[-- 2 -- 4 5]
[False False False False]
[ True  True  True  True]
[False  True False  True]


In [48]:
arr[mask]

array([1, 3])


## Structured Arrays
NumPy allows for the creation of structured arrays, which are arrays of structured data types that can be used to represent more complex data structures than regular arrays. They can be used to store and manipulate heterogeneous data, such as data from a database or spreadsheet.

In [49]:
# Creating a structured array
person_dtype = np.dtype([('name', 'S10'), ('age', 'i4'), ('height', 'f'), ('is_married', 'b')])
person_arr = np.array([('John', 25, 1.75, True), ('Jane', 30, 1.68, False)], dtype=person_dtype)
print(person_arr)

# Accessing fields in a structured array
print(person_arr['name'])
print(person_arr['age'])
print(person_arr['is_married'])

[(b'John', 25, 1.75, 1) (b'Jane', 30, 1.68, 0)]
[b'John' b'Jane']
[25 30]
[1 0]


NumPy exercises covering the topics previously mentioned:

1. Create a 1D NumPy array with the numbers from 1 to 10.
2. Create a 2D NumPy array with shape (3, 3) with random integer values between 0 and 9.
3. Use indexing to access the second element of the 1D array and the (1, 1) element of the 2D array.
4. Use slicing to create a new array with the last five elements of the 1D array and the first two rows of the 2Darray.
5. Use basic operations (+, -, *, /, **) to perform calculations on the 1D and 2D arrays.
6. Use a universal function (e.g. np.sqrt()) to calculate the square root of all elements in the 1D array.
7. Use broadcasting to add a scalar value of 10 to each element in the 1D array and each element in the secondcolumn of the 2D array.
8. Use array shape manipulation functions (e.g. np.reshape(), np.transpose()) to manipulate the shape of the 1D and2D arrays.
9. Use masking and Boolean logic to create a new array with all elements of the 1D array greater than 5 and allelements of the 2D array less than 5.
10. Create a structured array with two fields, 'name' and 'age', and add data for three people.

> Content created by **Carlos Cruz-Maldonado**.  
> Feel free to ping me at any time.